-- CreateTable
CREATE TABLE `Kriteria` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `HM` DOUBLE NOT NULL,
    `HS` DOUBLE NOT NULL,
    `HK` DOUBLE NOT NULL,
    `HC` DOUBLE NOT NULL,
    `HJ` DOUBLE NOT NULL,
    `MS` DOUBLE NOT NULL,
    `MK` DOUBLE NOT NULL,
    `MC` DOUBLE NOT NULL,
    `MJ` DOUBLE NOT NULL,
    `SK` DOUBLE NOT NULL,
    `SC` DOUBLE NOT NULL,
    `SJ` DOUBLE NOT NULL,
    `KC` DOUBLE NOT NULL,
    `KJ` DOUBLE NOT NULL,
    `CJ` DOUBLE NOT NULL,
    `userId` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Kriteria_userId_key`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Kriteria` ADD CONSTRAINT `Kriteria_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
